# SALVAR UM CLASSIFICADOR TREINADO para uso no front-end

In [4]:
# CARREGAMENTO DO MODELO
import pickle
with open('Credito.pkl', 'rb') as f:
    X_credit_treinamento, y_credit_treinamento, X_credit_teste, y_credit_teste = pickle.load(f)

In [5]:
X_credit_treinamento.shape, y_credit_treinamento.shape

((1500, 3), (1500,))

In [6]:
X_credit_teste.shape, y_credit_teste.shape

((500, 3), (500,))

In [7]:
# UNIR OS DADOS 
import numpy as np
X_credit = np.concatenate((X_credit_treinamento, X_credit_teste), axis=0)
y_credit = np.concatenate((y_credit_treinamento, y_credit_teste), axis=0)

In [8]:
# Verificar apos a uniao dos dados
X_credit.shape, y_credit.shape

((2000, 3), (2000,))

In [9]:
# importacao dos algoritmos selecionados como melhores
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [10]:
# Treinamento da rede neural com as metricas selecionadas 
classficador_rede_neural = MLPClassifier(activation='relu', batch_size=56, solver='adam')
classficador_rede_neural.fit(X_credit, y_credit)

C:\Users\LeonelSilima\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(batch_size=56)

In [11]:
# Treinamento com Arvor de decisao
classificador_arvore = DecisionTreeClassifier(criterion='entropy', min_samples_leaf=1, min_samples_split=5, splitter='best')
classificador_arvore.fit(X_credit, y_credit)

DecisionTreeClassifier(criterion='entropy', min_samples_split=5)

In [86]:
#Treinamento com SVM
classificador_SVM = SVC(C=2.0, kernel='rbf', probability=True)
classificador_SVM.fit(X_credit, y_credit)

SVC(C=2.0, probability=True)

In [87]:
# SALVAR OS CLASSIFICADOR
import pickle
pickle.dump(classficador_rede_neural, open('NEURAL_NETWORK_finalizado.sav', 'wb'))
pickle.dump(classificador_arvore, open('DECISION_TREE_finalizado.sav', 'wb'))
pickle.dump(classificador_SVM, open('SVM_finalizado.sav', 'wb'))

# CARREGAR CLASSIFICADOR TREINADO E TESTAR O FUNCIONAMENTO

In [88]:
#carregamento dos modelos
import pickle
rede_neural = pickle.load(open('rede_neural_finalizado.sav', 'rb'))
arvore = pickle.load(open('arvore_finalizado.sav', 'rb'))
SVM = pickle.load(open('SVM_finalizado.sav', 'rb'))

In [15]:
# Simulacao de funcionamento
novo_registo = X_credit[1990] # A POSICAO DAS CARATERISTICAS DO CLIENTE
novo_registo

array([ 0.33102925, -0.59722855,  1.1969192 ])

In [16]:
novo_registo.shape

(3,)

In [17]:
novo_registo = novo_registo.reshape(1, -1)
novo_registo.shape

(1, 3)

In [18]:
rede_neural.predict(novo_registo) # 1 Corresponde ao cliente que NAO paga a divida

array([1], dtype=int64)

In [19]:
arvore.predict(novo_registo) # 1 Corresponde ao cliente que NAO paga a divida

array([1], dtype=int64)

In [20]:
SVM.predict(novo_registo) # 0 Corresponde ao cliente que PAGA a divida LOGO este algoritmo apresenta incosistencias

array([1], dtype=int64)

# COMBINACAO DE CLASSIFICADORES

In [121]:
# PREVISAO DOS ALGORITMOS
novo_registo = X_credit[0] # POSICAO DOS DADOS A PREVER O RESULTADO - HISTORICOS
novo_registo = novo_registo.reshape(1, -1) # PARA COLOCAR NO FORMATO DE MATRIZ
novo_registo, novo_registo.shape

(array([[-1.3754462 ,  0.50631087,  0.10980934]]), (1, 3))

In [122]:
resposta_rede_neural = rede_neural.predict(novo_registo)
resposta_arvore = arvore.predict(novo_registo)
resposta_SVM = SVM.predict(novo_registo)

In [123]:
resposta_rede_neural[0], resposta_arvore[0], resposta_SVM[0] # TODOS CLASSIFICADORES INDICAM QUE OS CLIENTES PAGAM O EMPRESTIMO

(0, 0, 0)

# CRIANDO RESULTADOS PARA UTILIZADOR

In [140]:
paga = 0
nao_paga = 1

if resposta_rede_neural[0] == 1:
    nao_paga +=1
else:
    paga +=1
if resposta_arvore[0] == 1:
    nao_paga +=1
else:
    paga +=1
if resposta_SVM[0] == 1:
    nao_paga +=1
else:
    paga +=1
if paga > nao_paga:
    texto = ('O cliente pagara o emprestimo')
    texto = texto.upper()
    print(texto)
elif paga == nao_paga:
    print('Empate, mais garantias devem ser revisto')
else:
    print('O cliente nao paga emprestimo')

O CLIENTE PAGARA O EMPRESTIMO


# REJEICAO DA PROBABILIDADE

In [142]:
novo_registo = X_credit[1991] # POSICAO DOS DADOS A PREVER O RESULTADO - HISTORICOS
novo_registo = novo_registo.reshape(1, -1) # PARA COLOCAR NO FORMATO DE MATRIZ
novo_registo, novo_registo.shape

(array([[-1.37924999,  0.83062478, -0.82824438]]), (1, 3))

In [126]:
resposta_rede_neural = rede_neural.predict(novo_registo)
resposta_arvore = arvore.predict(novo_registo)
resposta_SVM = SVM.predict(novo_registo)

In [127]:
resposta_rede_neural[0], resposta_arvore[0], resposta_SVM[0] # TODOS CLASSIFICADORES INDICAM QUE OS CLIENTES PAGAM O EMPRESTIMO

(0, 0, 0)

In [128]:
probabilidade_rede_neural = rede_neural.predict_proba(novo_registo) # Visualizacao das probabilidades das classes
probabilidade_rede_neural 

array([[1.00000000e+00, 8.10398435e-22]])

In [129]:
confianca_rede_neural = probabilidade_rede_neural.max() # para verificar a confianca da probabilidade
confianca_rede_neural

1.0

In [130]:
probabilidade_arvore = arvore.predict_proba(novo_registo) #100% de probabilidade dar certo
probabilidade_arvore

array([[1., 0.]])

In [131]:
confianca_arvore = probabilidade_arvore.max() # para verificar a confianca da probabilidade
confianca_arvore

1.0

In [132]:
probabilidade_SVM = SVM.predict_proba(novo_registo)
probabilidade_arvore

array([[1., 0.]])

In [133]:
confianca_SVM = probabilidade_SVM.max() # para verificar a confianca da probabilidade
confianca_SVM

0.9999991935649787

In [135]:
paga = 0
nao_paga = 1
confianca_minima = 0.9999999999
algoritmos = 0 # para identificar quantos algoritmos foram utilizados

if confianca_rede_neural >= confianca_minima:
    algoritmos += 1
    if resposta_rede_neural[0] == 1:
        nao_paga +=1
    else:
        paga +=1
if confianca_arvore >= confianca_minima:
    algoritmos += 1
    if resposta_arvore[0] == 1:
        nao_paga +=1
    else:
        paga +=1
if confianca_SVM >= confianca_minima:
    algoritmos += 1
    if resposta_SVM[0] == 1:
        nao_paga +=1
    else:
        paga +=1
if paga > nao_paga:
        texto = ('O cliente pagara o emprestimo baseado em {} Algoritmos' .format(algoritmos))
        texto = texto.upper()
        print(texto)
elif paga == nao_paga:
    print('Empate, mais garantias devem ser revisto')
else:
    print('O cliente nao paga emprestimo')

O CLIENTE PAGARA O EMPRESTIMO BASEADO EM 2 ALGORITMOS
